### ISSUE TITLE
Autocomplete makes custom commands unusable on iOS

### ISSUE THREAD

**Issue by pchertok** [furusystems/DConsole#2]
Because of the hint system when you start to type a command into the console - the autocomplete feature ends up selecting the whole typed word - so when you type the next letter of the command the whole word gets replaced with the next character.  It would be awesome if there was a way to disable the autocomplete.

**Comment by Sunjammer** [comment]
On _iOS_ wow, did not see that coming :)

**Comment by BigPhilCombo** [comment]
Oh yeah - it's super useful.  Thanks for continuing to support this project
btw.

On Mon, Mar 2, 2015 at 9:08 AM, Andreas Rønning notifications@github.com
wrote:

> On _iOS_ wow, did not see that coming :)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/furusystems/DConsole/issues/2#issuecomment-76716958.

## 

Phillip Chertok
